// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzuqzxwwadmuymyatydi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dXF6eHd3YWRtdXlteWF0eWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTE5MzEsImV4cCI6MjA2ODA4NzkzMX0.y2GsfW10i3wQGCOev9vgS0dmQZmCK7hCrkNsTM8DHjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});